### ISSUE TITLE
return default object instead of function in service/datahandler

### ISSUE THREAD

**Issue by moficodes** [bee-travels/node-service-template#2]
```
import ExampleError from "./../errors/ExampleError";

export async function getData() {
  throw new ExampleError("TODO: Implement me!");
}
```

This is how we do this now.

I suggest we change this to 

```
import ExampleError from "./../errors/ExampleError";

async function getData() {
  throw new ExampleError("TODO: Implement me!");
}

export default {getData};
```

Pros: 
- Since the export will be tied to an object we will have an easier time mocking it with stub
- Import becomes simpler with importing any meaning full name from our route
- we get a go like structure where each function is connected to the module its coming from.

Cons: 
- A bit more verbose (which could also be a good thing)

**Comment by bourdakos1** [comment]
Are these actually different?

**Comment by bourdakos1** [comment]
I'm going to veto this, I believe this is an anti pattern. If you really want them in one object you can import like:
```js
import * as dataService from "./dataService"

dataService.getData()
```

I think the only time to use default exports is if the file is only exporting one thing and will always only export one thing. Think a class or a react component.

also, not that this matters for us because this is not a library and it's a server, but I think this would break tree-shaking because you would have to always import everything from the file and not just what you need

**Comment by moficodes** [comment]
`import * as dataService from "./dataService"`
Breaks code coverage in test

**Comment by moficodes** [comment]
@bourdakos1

**Comment by bourdakos1** [comment]
oh well 🤷‍♂️
